INSERT INTO CURRENCY VALUES('USD', '美金');
INSERT INTO CURRENCY VALUES('GBP', '英鎊');
INSERT INTO CURRENCY VALUES('EUR', '歐元');
INSERT INTO CURRENCY VALUES('JPY', '日幣');
INSERT INTO CURRENCY VALUES('HKD', '港幣修改');